
DROP TABLE COMMENTBOARD;
DROP SEQUENCE COMMENTSEQ;


CREATE SEQUENCE COMMENTSEQ;
--댓글 글 번호, 게시글 글 번호, 댓글 작성자, 댓글 작성일, 부모글, 댓글 내용
CREATE TABLE COMMENTBOARD(

	COMMENTBOARD_NO NUMBER PRIMARY KEY,
	COMMENTBOARD_BOARDNO NUMBER NOT NULL REFERENCES REVIEWBOARD(REVIEWBOARD_NO),
	COMMENTBOARD_ID VARCHAR2(300) NOT NULL,
	COMMENTBOARD_CONTENT CLOB NOT NULL,
	COMMENTBOARD_REGDATE DATE NOT NULL,
	COMMENTBOARD_DELFLAG VARCHAR2(2) NOT NULL

);

SELECT * FROM COMMENTBOARD;

ALTER TABLE COMMENTBOARD ADD CONSTRAINT COMMENTBOARD_DELFLAG_CK CHECK(COMMENTBOARD_DELFLAG IN ('Y','N'));

ALTER TABLE COMMENTBOARD MODIFY(COMMENTBOARD_DELFLAG DEFAULT 'N'); 

INSERT INTO COMMENTBOARD VALUES(COMMENTSEQ.NEXTVAL, 186, 'admin', 'test01', SYSDATE, 'N' );

INSERT INTO COMMENTBOARD VALUES(COMMENTSEQ.NEXTVAL, )

SELECT * FROM COMMENTBOARD WHERE COMMENTBOARD_BOARDNO=186 ORDER BY COMMENTBOARD_NO;